package org.example.auctionbot;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class Constants {
    public static final String BAZAAR_ENDPOINT = "https://api.hypixel.net/skyblock/bazaar?key=%s";
    public static final String AUCTION_ENDPOINT = "https://api.hypixel.net/skyblock/auctions?key=%s&page=%d";
    public static final String PROFILE_ENDPOINT = "https://api.hypixel.net/skyblock/profile?key=%s&profile=%s"; // Note: profile is UUID
    public static final String TOKEN_TEST = "https://api.hypixel.net/key?key=%s";

    public static final double PERCENTAGE_VALUE = 0.85; // Example value, adjust as needed

    public static final Map<String, Integer> ENCHANTS;
    static {
        Map<String, Integer> aMap = new HashMap<>();
        aMap.put("dragon_hunter", 5);
        aMap.put("ultimate_one_for_all", 1);
        aMap.put("ultimate_wise", 5);
        aMap.put("ultimate_swarm", 5);
        aMap.put("ultimate_chimera", 5);
        aMap.put("ultimate_soul_eater", 5);
        aMap.put("ultimate_inferno", 5);
        aMap.put("ultimate_bank", 5);
        aMap.put("ultimate_combo", 5);
        aMap.put("ultimate_fatal_tempo", 5);
        aMap.put("ultimate_legion", 5);
        aMap.put("ultimate_rend", 5);
        aMap.put("ultimate_shortbow", 5);
        aMap.put("ultimate_reiterate", 5);
        aMap.put("ultimate_bob_and_weave", 5);
        aMap.put("ultimate_no_pain_no_gain", 5);
        aMap.put("ultimate_last_stand", 5);
        aMap.put("ultimate_ultimate_protection", 5);
        aMap.put("ultimate_ultimate_efficiency", 5);
        aMap.put("ultimate_ultimate_fortune", 5);
        aMap.put("ultimate_ultimate_looting", 5);
        aMap.put("ultimate_ultimate_scavenger", 5);
        aMap.put("ultimate_ultimate_experience", 5);
        aMap.put("ultimate_ultimate_cultivating", 5);
        aMap.put("ultimate_ultimate_dedication", 5);
        aMap.put("ultimate_ultimate_blessing", 5);
        aMap.put("ultimate_ultimate_compact", 5);
        aMap.put("ultimate_ultimate_telepathy", 5);
        aMap.put("ultimate_ultimate_growth", 5);
        aMap.put("ultimate_ultimate_rejuvenate", 5);
        aMap.put("ultimate_ultimate_counter_strike", 5);
        aMap.put("ultimate_ultimate_sharpness", 5);
        aMap.put("ultimate_ultimate_smite", 5);
        aMap.put("ultimate_ultimate_bane_of_arthropods", 5);
        aMap.put("ultimate_ultimate_ender_slayer", 5);
        aMap.put("ultimate_ultimate_giant_killer", 5);
        aMap.put("ultimate_ultimate_execute", 5);
        aMap.put("ultimate_ultimate_critical", 5);
        aMap.put("ultimate_ultimate_first_strike", 5);
        aMap.put("ultimate_ultimate_triple_strike", 5);
        aMap.put("ultimate_ultimate_vicious", 5);
        aMap.put("ultimate_ultimate_knockback", 5);
        aMap.put("ultimate_ultimate_fire_aspect", 5);
        aMap.put("ultimate_ultimate_looting", 5);
        aMap.put("ultimate_ultimate_scavenger", 5);
        aMap.put("ultimate_ultimate_experience", 5);
        aMap.put("ultimate_ultimate_luck", 5);
        aMap.put("ultimate_ultimate_respiration", 5);
        aMap.put("ultimate_ultimate_aqua_affinity", 5);
        aMap.put("ultimate_ultimate_thorns", 5);
        aMap.put("ultimate_ultimate_depth_strider", 5);
        aMap.put("ultimate_ultimate_frost_walker", 5);
        aMap.put("ultimate_ultimate_curse_of_vanishing", 5);
        aMap.put("ultimate_ultimate_curse_of_binding", 5);
        aMap.put("ultimate_ultimate_mending", 5);
        aMap.put("ultimate_ultimate_unbreaking", 5);
        aMap.put("ultimate_ultimate_silk_touch", 5);
        aMap.put("ultimate_ultimate_fortune", 5);
        aMap.put("ultimate_ultimate_efficiency", 5);
        aMap.put("ultimate_ultimate_punch", 5);
        aMap.put("ultimate_ultimate_flame", 5);
        aMap.put("ultimate_ultimate_power", 5);
        aMap.put("ultimate_ultimate_infinity", 5);
        aMap.put("ultimate_ultimate_piercing", 5);
        aMap.put("ultimate_ultimate_multishot", 5);
        aMap.put("ultimate_ultimate_quick_charge", 5);
        aMap.put("ultimate_ultimate_loyalty", 5);
        aMap.put("ultimate_ultimate_impaling", 5);
        aMap.put("ultimate_ultimate_riptide", 5);
        aMap.put("ultimate_ultimate_channeling", 5);
        aMap.put("ultimate_ultimate_trident_killer", 5);
        aMap.put("ultimate_ultimate_soulbound", 5);
        aMap.put("ultimate_ultimate_expertise", 5);
        aMap.put("ultimate_ultimate_compact", 5);
        aMap.put("ultimate_ultimate_telepathy", 5);
        aMap.put("ultimate_ultimate_smelting", 5);
        aMap.put("ultimate_ultimate_magnet", 5);
        aMap.put("ultimate_ultimate_harvesting", 5);
        aMap.put("ultimate_ultimate_replenish", 5);
        aMap.put("ultimate_ultimate_sugar_rush", 5);
        aMap.put("ultimate_ultimate_experience", 5);
        aMap.put("ultimate_ultimate_cultivating", 5);
        aMap.put("ultimate_ultimate_dedication", 5);
        aMap.put("ultimate_ultimate_blessing", 5);
        aMap.put("ultimate_ultimate_compact", 5);
        aMap.put("ultimate_ultimate_telepathy", 5);
        aMap.put("ultimate_ultimate_growth", 5);
        aMap.put("ultimate_ultimate_rejuvenate", 5);
        aMap.put("ultimate_ultimate_counter_strike", 5);
        aMap.put("ultimate_ultimate_sharpness", 5);
        aMap.put("ultimate_ultimate_smite", 5);
        aMap.put("ultimate_ultimate_bane_of_arthropods", 5);
        aMap.put("ultimate_ultimate_ender_slayer", 5);
        aMap.put("ultimate_ultimate_giant_killer", 5);
        aMap.put("ultimate_ultimate_execute", 5);
        aMap.put("ultimate_ultimate_critical", 5);
        aMap.put("ultimate_ultimate_first_strike", 5);
        aMap.put("ultimate_ultimate_triple_strike", 5);
        aMap.put("ultimate_ultimate_vicious", 5);
        aMap.put("ultimate_ultimate_knockback", 5);
        aMap.put("ultimate_ultimate_fire_aspect", 5);
        aMap.put("ultimate_ultimate_looting", 5);
        aMap.put("ultimate_ultimate_scavenger", 5);
        aMap.put("ultimate_ultimate_experience", 5);
        aMap.put("ultimate_ultimate_luck", 5);
        aMap.put("ultimate_ultimate_respiration", 5);
        aMap.put("ultimate_ultimate_aqua_affinity", 5);
        aMap.put("ultimate_ultimate_thorns", 5);
        aMap.put("ultimate_ultimate_depth_strider", 5);
        aMap.put("ultimate_ultimate_frost_walker", 5);
        aMap.put("ultimate_ultimate_curse_of_vanishing", 5);
        aMap.put("ultimate_ultimate_curse_of_binding", 5);
        aMap.put("ultimate_ultimate_mending", 5);
        aMap.put("ultimate_ultimate_unbreaking", 5);
        aMap.put("ultimate_ultimate_silk_touch", 5);
        aMap.put("ultimate_ultimate_fortune", 5);
        aMap.put("ultimate_ultimate_efficiency", 5);
        aMap.put("ultimate_ultimate_punch", 5);
        aMap.put("ultimate_ultimate_flame", 5);
        aMap.put("ultimate_ultimate_power", 5);
        aMap.put("ultimate_ultimate_infinity", 5);
        aMap.put("ultimate_ultimate_piercing", 5);
        aMap.put("ultimate_ultimate_multishot", 5);
        aMap.put("ultimate_ultimate_quick_charge", 5);
        aMap.put("ultimate_ultimate_loyalty", 5);
        aMap.put("ultimate_ultimate_impaling", 5);
        aMap.put("ultimate_ultimate_riptide", 5);
        aMap.put("ultimate_ultimate_channeling", 5);
        aMap.put("ultimate_ultimate_trident_killer", 5);
        aMap.put("ultimate_ultimate_soulbound", 5);
        aMap.put("ultimate_ultimate_expertise", 5);
        aMap.put("ultimate_ultimate_compact", 5);
        aMap.put("ultimate_ultimate_telepathy", 5);
        aMap.put("ultimate_ultimate_smelting", 5);
        aMap.put("ultimate_ultimate_magnet", 5);
        aMap.put("ultimate_ultimate_harvesting", 5);
        aMap.put("ultimate_ultimate_replenish", 5);
        aMap.put("ultimate_ultimate_sugar_rush", 5);
        ENCHANTS = Collections.unmodifiableMap(aMap);
    }
}